item_list = [
    [{'pickaxe': 'Used to mine rocks'}, 'None', {}],
    [{'fishingrod': 'Used to fish'}, 'None', {}],
    [{'TinBoots': 'Gives +2 Defense Skill'}, 'Feet', {'Defense': 2}],
    [{'TinLeggings': 'Gives +2 Defense Skill'}, 'Legs', {'Defense': 2}],
    [{'TinChestplate': 'Gives +2 Defense Skill'}, 'Chest', {'Defense': 2}],
    [{'TinHelmet': 'Gives +2 Defense Skill'}, 'Head', {'Defense': 2}],
    [{'ThiefHelmet': 'Gives +2 Stealing, +2 Agility Skill'}, 'Head', {'Stealing': 2, 'Agility': 2}],
    [{'ThiefChestplate': 'Gives +2 Stealing, +2 Agility Skill'}, 'Chest', {'Stealing': 2, 'Agility': 2}],
    [{'ThiefLeggings': 'Gives +2 Stealing, +2 Agility Skill'}, 'Legs', {'Stealing': 2, 'Agility': 2}],
    [{'ThiefBoots': 'Gives +2 Stealing, +2 Agility Skill'}, 'Feet', {'Stealing': 2, 'Agility': 2}],
    [{'WarriorBoots': 'Gives +2 Combat Skill'}, 'Feet', {'Combat': 2}],
    [{'WarriorLeggings': 'Gives +2 Combat Skill'}, 'Legs', {'Combat': 2}],
    [{'WarriorChestplate': 'Gives +2 Combat Skill'}, 'Chest', {'Combat': 2}],
    [{'WarriorHelmet': 'Gives +2 Combat Skill'}, 'Head', {'Combat': 2}],
    [{'FishBoots': 'Gives +2 Fishing Skill'}, 'Feet', {'Fishing': 2}],
    [{'FishChestplate': 'Gives +2 Fishing Skill'}, 'Chest', {'Fishing': 2}],
    [{'FishLeggings': 'Gives +2 Fishing Skill'}, 'Legs', {'Fishing': 2}],
    [{'FishHelmet': 'Gives +2 Fishing Skill'}, 'Head', {'Fishing': 2}],
    [{'MinerBoots': 'Gives +2 Mining Skill'}, 'Feet', {'Mining': 2}],
    [{'MinerHelmet': 'Gives +2 Mining Skill'}, 'Head', {'Mining': 2}],
    [{'MinerChestplate': 'Gives +2 Mining Skill'}, 'Chest', {'Mining': 2}],
    [{'MinerLeggings': 'Gives +2 Mining Skill'}, 'Legs', {'Mining': 2}],
    [{'IronSword': 'Gives +4 Combat Skill'}, 'Hand', {'Combat': 4}],
    [{'MagicStaff': 'Gives +4 Magic Skill'}, 'Hand', {'Magic': 4}],
    [{'GemFishingRod': 'Gives +5 Fishing Skill'}, 'Hand', {'Fishing': 5}],
    [{'LuckyStick': 'Gives +5 Luck Skill'}, 'Hand', {'Luck': 5}],
    [{'BonerSword': 'Gives +6 Agility Skill'}, 'Hand', {'Agility': 6}],
    [{'CombatChestplate': 'Gives +2 Combat Skill'}, 'Chest', {'Combat': 2}],
    [{'ChampionChestplate': 'Gives +5 Combat Skill'}, 'Chest', {'Combat': 5}],
    [{'WarBornChestplate': 'Gives +10 Combat Skill'}, 'Chest', {'Combat': 10}],
    [{'MagicChestplate': 'Gives +2 Magic Skill'}, 'Chest', {'Magic': 2}],
    [{'ElementalChestplate': 'Gives +5 Magic Skill'}, 'Chest', {'Magic': 5}],
    [{'ArchMageChestplate': 'Gives +10 Magic Skill'}, 'Chest', {'Magic': 10}],
    [{'AncientChestplate': 'Gives +3 Health Skill'}, 'Chest', {'Health': 3}],
    [{'WandOfHealing': 'Gives +4 Healing Skill'}, 'Hand', {'Healing': 3}],
    [{'ElectrumWand': 'Gives +5 Magic Skill'}, 'Hand', {'Magic': 5}],
    [{'Shield': 'Grants 3 shield each turn'}, 'Hand', {}],
    [{'EternalHelmet': 'Gives +5 Defense Skill, +5 Health Skill'}, 'Head', {'Defense': 5, 'Health': 5}],
    [{'EternalChestplate': 'Gives +5 Defense Skill, +5 Health Skill'}, 'Chest', {'Defense': 5, 'Health': 5}],
    [{'EternalLeggings': 'Gives +5 Defense Skill, +5 Health Skill'}, 'Legs', {'Defense': 5, 'Health': 5}],
    [{'EternalBoots': 'Gives +5 Defense Skill, +5 Health Skill'}, 'Feet', {'Defense': 5, 'Health': 5}],
    [{'EternalGuardianShield': 'Gives +15 Defense Skill'}, 'Hand', {'Defense': 15}],
    [{'AssassinsHelmet': 'Gives +3 Agility Skill'}, 'Head', {'Agility': 3}],
    [{'AssassinsChestplate': 'Gives +3 Agility Skill'}, 'Chest', {'Agility': 3}],
    [{'AssassinsLeggings': 'Gives +3 Agility Skill'}, 'Legs', {'Agility': 3}],
    [{'AssassinsBoots': 'Gives +3 Agility Skill'}, 'Feet', {'Agility': 3}],
    [{'HunterRing': 'Gives +1 Combat Skill, +1 Agility Skill, +1 Magic Skill'}, 'Finger', {'Agility': 1, 'Magic': 1, 'Combat': 1}],
    [{'SorcererWand': 'Gives +5 Magic Skill, +2 Defense Skill'}, 'Hand', {'Magic': 5, 'Defense': 2}],
    [{'MagicDagger': 'Gives +3 Magic Skill, +4 Agility Skill'}, 'Hand', {'Magic': 3, 'Agility': 4}],
    [{'DiabloRing': 'Gives +4 Magic Skill'}, 'Ring', {'Magic': 4}],
    [{'InfinityBoots': 'Gives +8 Magic Skill'}, 'Feet', {'Magic': 8}],
    [{'SpectralHelmet': 'Gives +6 Magic Skill'}, 'Head', {'Magic': 6}],
    [{'SpectralChestplate': 'Gives +6 Magic Skill'}, 'Chest', {'Magic': 6}],
    [{'SpectralLeggings': 'Gives +6 Magic Skill'}, 'Legs', {'Magic': 6}],
    [{'SpectralBoots': 'Gives +6 Magic Skill'}, 'Feet', {'Magic': 6}],
    [{'BasaltShield': 'Gives +8 Defense Skill'}, 'Hand', {'Defense': 8}],
    [{'BasaltHelmet': 'Gives +8 Defense Skill, -4 Health Skill'}, 'Head', {'Defense': 8, 'Health': -4}],
    [{'SkeletalChestplate': 'Gives +5 Agility Skill'}, 'Chest', {'Agility': 5}],
    [{'SteelHelmet': 'Gives +4 Combat Skill'}, 'Head', {'Combat': 4}],
    [{'SteelChestplate': 'Gives +4 Combat Skill'}, 'Chest', {'Combat': 4}],
    [{'SteelLeggings': 'Gives +4 Combat Skill'}, 'Legs', {'Combat': 4}],
    [{'SteelBoots': 'Gives +4 Combat Skill'}, 'Feet', {'Combat': 4}],
    [{'DarkBoots': 'Gives +9 Agility Skill'}, 'Feet', {'Agility': 9}],
    [{'AbyssalDagger': 'Gives +3 Agility Skill, +2 Defense Skill'}, 'Hand', {'Agility': 3, 'Defense': 2}],
    [{'AngelHelmet': 'Gives +10 Healing Skill'}, 'Head', {'Healing': 10}],
    [{'AngelChestplate': 'Gives +10 Healing Skill'}, 'Chest', {'Healing': 10}],
    [{'AngelLeggings': 'Gives +10 Healing Skill'}, 'Legs', {'Healing': 10}],
    [{'AngelBoots': 'Gives +10 Healing Skill'}, 'Feet', {'Healing': 10}],
    [{'StaffOfAegis': 'Gives +18 Magic Skill'}, 'Hand', {'Magic': 18}],
    [{'LavaSword': 'Gives +12 Combat Skill'}, 'Hand', {'Combat': 12}],
    [{'PurityChestplate': 'Gives +6 Health Skill'}, 'Chest', {'Health': 6}],
    [{'CursedMask': 'Gives -5 Defense Skill, -5 Luck Skill, +8 Magic Skill'}, 'Head', {'Magic': 8, 'Luck': -5, 'Defense': -5}],
    [{'TormentShard': 'Gives +3 Magic Skill, +3 Healing Skill'}, 'Hand', {'Magic': 3, 'Healing': 3}],
    [{'HallowedHelmet': 'Gives +4 Defense Skill, +6 Luck Skill'}, 'Head', {'Defense': 4, 'Luck': 6}],
    [{'HallowedChestplate': 'Gives +4 Defense Skill, +6 Luck Skill'}, 'Chest', {'Defense': 4, 'Luck': 6}],
    [{'HallowedLeggings': 'Gives +4 Defense Skill, +6 Luck Skill'}, 'Legs', {'Defense': 4, 'Luck': 6}],
    [{'HallowedBoots': 'Gives +4 Defense Skill, +6 Luck Skill'}, 'Feet', {'Defense': 4, 'Luck': 6}],
    [{'HallowedSpear': 'Gives +2 Defense Skill, +8 Combat Skill'}, 'Hand', {'Defense': 2, 'Combat': 8}],
    [{'PunySword': 'Gives +1 Combat Skill'}, 'Hand', {'Combat': 1}],
    [{'SteelGreatSword': 'Gives +6 Combat Skill'}, 'Hand', {'Combat': 6}],
    [{'OldIronChestplate': 'Gives +2 Defense Skill'}, 'Chest', {'Defense': 2}],
    [{'SlimeRing': 'Gives +4 Magic Skill, +4 Agility Skill'}, 'Finger', {'Magic': 4, 'Agility': 4}],
    [{'Katana': 'Gives +3 Combat Skill, +3 Agility Skill'}, 'Hand', {'Combat': 3, 'Agility': 3}],
    [{'WarlockLeggings': 'Gives +5 Magic Skill, -3 Healing Skill'}, 'Legs', {'Magic': 5, 'Healing': -3}],
    [{'WarlockBoots': 'Gives +5 Magic Skill, -3 Healing Skill'}, 'Feet', {'Magic': 5, 'Healing': -3}],
    [{'MagicRing': 'Gives +2 Magic Skill'}, 'Finger', {'Magic': 2}],
    [{'Slash':  "(combat) Damage - 3"}, 'Card', {'Combat': 3}],
    [{'Defend':  "Shield - 5"}, 'Card', {'Defense': 5}],
    [{'Charge': "(agility) Damage - 2, Extra Card Draw"}, 'Card', {'Agility': 2, 'Draw': 1}],
    [{'Recharge': "Heal - 8"}, 'Card', {'Healing': 8}],
    [{'Punch': "(agility) Damage - 4"}, 'Card', {'Agility': 4}],
    [{'Shieldbash': "(combat) Damage - 5"}, 'Card', {'Combat': 5}],
    [{'Bash': "(combat) Damage - 2, Shield - 4"}, 'Card', {'Combat': 2, 'Defense': 4}],
    [{'Slice': "(agility) Damage - 4, Heal - 4"}, 'Card', {'Agility': 4, 'Healing': 4}],
    [{'Snipe': "(magic) Damage - 7"}, 'Card', {'Magic': 7}],
    [{'Trickshot': "(magic) Damage - 5, Shield - 3"}, 'Card', {'Magic': 5, 'Defense': 3}],
    [{'Whirlwind': "(combat) Damage - 5, Extra Card Draw"}, 'Card', {'Combat': 5, 'Draw': 1}],
    [{'Bomb': "(agility) Damage - 30, Bonus - Gets permanently destroyed"}, 'Card', {'Agility': 30, 'Destroy': 1}],
    [{'Towershield': "Shield - 12"}, 'Card', {'Defense': 12}],
    [{'Regeneration': "Heal - 25"}, 'Card', {'Healing': 25}],
    [{'Onepunch': "(combat) Damage - 30"}, 'Card', {'Combat': 30}],
    [{'Slam': "(combat) Damage - 5, Shield - 5, Heal - 4"}, 'Card', {'Combat': 5, 'Defense': 5, 'Healing': 4}],
    [{'Incinerate': "(magic) Damage - 11"}, 'Card', {'Magic': 11}],
    [{'Devastate': "(magic) Damage - 8, Shield - 2"}, 'Card', {'Magic': 8, 'Defense': 2}],
    [{'Bite': "(agility) Damage - 10"}, 'Card', {'Agility': 10}],
    [{'Venom': "(magic) Damage - 3, Shield - 8"}, 'Card', {'Magic': 3, 'Defense': 8}],
    [{'Smash': "(combat) Damage - 3, Heal - 10"}, 'Card', {'Agility': 4, 'Healing': 4}],

    [{'Assassinate': "(agility) Damage - 9, + 3 if target below 20%"}, 'Card', {'Agility': 9, 'Finisher': 3}],
    [{'SkyShard': "(magic) Damage - 9, Extra Card Draw"}, 'Card', {'Magic': 9, 'Draw': 1}],
    [{'Stab': "(agility) Damage - 5, Extra Card Draw"}, 'Card', {'Agility': 5, 'Draw': 1}],
    [{'ShadowSlice': "(agility) Damage - 4, (magic) Damage - 2"}, 'Card', {'Agility': 4, 'Magic': 2}],
    [{'ShadowBeam': "(magic) Damage - 6, Shield - 7"}, 'Card', {'Magic': 6, 'Defense': 7}],
    [{'ShadowStep': "(magic) Damage - 1, Shield - 4"}, 'Card', {'Magic': 1, 'Defense': 4}],
    [{'DarkCharge': "(combat) Damage - 12, Extra Card Draw"}, 'Card', {'Magic': 6, 'Defense': 7}],
    [{'Shatter': "(combat) Damage - 9, Heal - 5"}, 'Card', {'Combat': 9, 'Healing': 5}],
    [{'RagingFury': "(combat) Damage - 6, Heal - 6"}, 'Card', {'Combat': 6, 'Healing': 6}],

]


def item_c(*args):  # 0 = this user_data, 1 = Command Class, 2 = all user data, 3 = extra args in list
    if len(args[3]) > 0:
        for item, slot, stats in item_list:
            for item_name, desc in item.items():
                if args[3][0] == item_name.lower():
                    return f"Info for  {item_name}: {slot}\n{desc}"
    else:
        return f"Incorrect use of item:\ntry 'item (item-name)'"
